name: Ionic CI
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
        working-directory: app
      - name: Build App
        run: npm run build
        working-directory: app
      - name: Test App
        run: npm run test
        working-directory: app
