name: Ionic CI
on:
  pull_request:
    branches:
      - master
      - develop
      - develop/frontend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run build:app
      - run: npm run test:app
