name: Node CI
on:
  pull_request:
    branches:
      - master
      - develop
      - develop/backend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm run build:server
      - run: npm run test:server


